name: Push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production_environment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm test      
      - uses: codecov/codecov-action@v1
        with:
          files: coverage/*.json
          name: codecov-GHA-test 
          fail_ci_if_error: true 
          verbose: true 
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        args: >
          -Dsonar.sources=lib/
          -Dsonar.test.exclusions=test/**
          -Dsonar.tests=test/
          -Dsonar.verbose=true